# Generated by Django 5.0 on 2024-01-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_thread_options_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
